### ISSUE TITLE
挖掘榜无法统计

### ISSUE THREAD

**Issue by XIMOYA** [Chlna6666/Ranking#4]
您好，我在使用您的插件时，输入/ranking:ranking destroys，提示挖掘榜已开启，但是我查询数据的时候，挖掘榜没有统计，并且屏幕右侧也无法显示挖掘榜

**Comment by Chlna6666** [comment]
没有日志无异于闭眼开车

**Comment by Chlna6666** [comment]
插件的配置文件 数据
服务端版本

**Comment by XIMOYA** [comment]
服务端是leaves1.20.1，配置文件如图所示，数据如图所示
![配置文件](https://github.com/user-attachments/assets/27ae9855-ed94-4258-8c77-5e14e38e959f)
![数据](https://github.com/user-attachments/assets/ec1b9f0b-1968-4cf3-bb5d-acb639bd4777)

**Comment by Chlna6666** [comment]
只有destroys是这样的吗

**Comment by XIMOYA** [comment]
是的

**Comment by Chlna6666** [comment]
感谢反馈
在#ce7abb2
操作时删除了 destroys 相关代码 导致无效

**Comment by Chlna6666** [comment]
已经修复带上传
